### PR TITLE
Upgrade WebRTC stack and Rust MSRV

### LINKED ISSUE #268: chore(native): migrate WebRTC stack after rtc-mdns restores Rust 1.89 compatibility
## Problem

Dependabot PR #265 proposes `webrtc` 0.17.2 → 0.20.0 for `clients/native`, but every workflow that builds the native client fails on the repository's supported Rust 1.89 toolchain:

```text
rtc-mdns-0.20.0/src/proto/mod.rs:633
Ipv4Addr::from_octets(a.a)
error[E0658]: use of unstable library feature `ip_from`
```

`Ipv4Addr::from_octets` is stable only from Rust 1.91. `webrtc` 0.20.0 depends on `rtc` 0.20.0, which unconditionally depends on `rtc-mdns` 0.20.0; the published feature sets do not remove mDNS. All published rtc-mdns 0.20 prereleases and 0.20.0 contain the same call, and the current upstream default branch remains affected.

Raising this repository's MSRV from 1.89 to 1.91 or carrying an unreviewed git/path patch is disproportionate for a routine dependency update. Keep `webrtc` 0.17 until an official compatible release is available.

## Upstream evidence

- Rust 1.91 release: https://github.com/rust-lang/rust/releases/tag/1.91.0
- Affected upstream source: https://github.com/webrtc-rs/rtc/blob/b1f30eae5ab10bd02688b91febb20e17d8fec159/rtc-mdns/src/proto/mod.rs#L633
- Published rtc-mdns versions: https://crates.io/crates/rtc-mdns/versions
- Exact Rust 1.89 compilation reports `ip_from` as unstable; Rust's source stability annotation records `since = "1.91.0"`.

## Acceptance criteria

- [ ] An official crates.io `rtc`/`webrtc` release builds on exact Rust 1.89, or the project makes an explicit coordinated MSRV decision.
- [ ] Migrate the native reference-client source for the WebRTC 0.20+ Sans-I/O rewrite; do not treat this as a lockfile-only update.
- [ ] `cargo +1.89.0 check --locked --manifest-path clients/native/Cargo.toml --all-features` passes.
- [ ] Native WebRTC, browser/native, and TURN-only interop runners pass.
- [ ] Relevant nightly multi-process/topology and starved-runtime matrices pass.
- [ ] No temporary git/path patch is introduced unless separately reviewed and justified for supply-chain/security reasons.

## Related

- Dependabot PR #265
- Issue #255 / the production zero-panic and exact-MSRV policy

### PR DESCRIPTION
**Pull request by wallstop**
## Summary

- raise the repository-wide exact Rust MSRV from 1.89 to 1.91
- migrate the standalone native reference client from webrtc-rs 0.17 to 0.20 and its async peer/polled data-channel APIs
- preserve Matchbox/browser signaling, deterministic crippled ICE, generation fencing, live TURN candidate proof, and the WebSocket relay floor
- bind concrete active interfaces so zero-STUN host candidates never advertise wildcard addresses, with scope-correct IPv6 handling
- make packet-loss recovery verification causal with a reserved clean-path PairRetry generation and separate reliable/unreliable release barriers
- update workflows, containers, Dependabot, documentation, and policy fixtures atomically

## Why

Issue #268 was blocked on the Rust-version decision required by WebRTC 0.20. The owner approved the coordinated MSRV raise, making this the highest-impact unblocked maintenance task. The upgrade removes the stale WebRTC dependency line while retaining the native reference client's gameplay-critical P2P and fallback behavior.

The initial dependency switch produced 31 compiler errors across removed builders, concrete peer/channel types, callbacks, ICE completion, and statistics. The port adopts the replacement APIs rather than carrying a source patch.

## Behavior and compatibility

- The established four-field `RTCIceCandidateInit` signaling projection remains exact; rtc 0.20's local-only `url` metadata is not leaked onto the wire.
- Candidate-pair statistics accept rtc 0.20's current raw/prefixed ID forms; the live TURN-only test proves relay/relay selection.
- Normal mode enumerates concrete active interfaces. A regression requires non-wildcard zero-STUN host candidates and scope-zero global/loopback IPv6 binds.
- Crippled mode preserves real offer/answer and gathering lifecycles with an isolated dummy UDP socket, configures the ICE agent for unconfigured TCP4 only, and drops inbound/outbound candidate signals. It therefore registers no local candidate and rejects SDP-embedded UDP candidates.
- Loss recovery now settles the complete old-generation signal ledger after fault lift, rebuilds every edge with a reserved bounded PairRetry generation, proves exactly one new channel-open per edge/label, releases reliable traffic only after every peer reports that rebuilt generation, and releases unreliable traffic only after the exact reliable ledger completes.
- Late-join status verification holds every live client at a shared success gate, waits exact reporter-to-observer fan-out counts, and compares each reporter's local transition sequence to every observer before teardown.
- Protocol-v2/v3 wire contracts and the universal WebSocket relay floor are unchanged.

## Validation

- exact Rust 1.91 root/native checks and MSRV consistency
- strict root and native Clippy, all targets/features, zero warnings
- complete root all-feature test gauntlet and repository policy suites
- native unit suite: 74 passed
- native WebRTC interoperability: 5/5 multi-process cells; the final late-join cell also passed 70 repeated targeted runs across the hardening loop
- browser/native interoperability: 9/9 Chromium cells
- TURN interoperability: relay-only positive and mismatched-secret fallback controls
- exact nightly WebRTC topology selection: 22/22 passed, including N=16 one-crippled fault; exact-head `4084bdb` also passed the complete two-phase hosted netem matrix
- root and native cargo-deny advisories/bans/licenses/sources
- CI configuration, document consistency, workflow hygiene, hook readiness, staged hooks, and `git diff --check`
- final independent adversarial review: PASS, zero actionable findings

## Hosted failure analysis

Two Verification Nightly attempts on `d328c2f` independently timed out in the N=8 mesh 1% packet-loss cell after the fault was lifted. Each run reached all topology and ICE barriers, but one different client in each attempt missed both application labels from one peer. The failure was in the test's simultaneous post-fault reliable/unreliable release boundary, not the upgraded signaling or topology logic. Commit `4084bdb` replaced that ambiguous boundary with the observable two-phase ledger barrier and passed the complete hosted Verification Nightly workflow, including the N=8 netem cell.

That head's standalone WebRTC workflow then exposed a separate autonomous-exit race in the late-join status oracle: one reporter produced a legitimate extra deduplicated transition during sibling teardown. The final test holds all live clients, awaits exact fan-out completion, checks reporter identity/order plus final connected state, and only then releases teardown. The subsequent exact head `1f76431` reproduced a real stuck SCTP association in the N=8 mesh netem cell: all pairs were historically open, but one reliable message never arrived after loss lift. Exact head `0b9b427` then reserved a clean PairRetry generation, settled all old signals before rebuild, required every edge to reconnect, and gated exchange on that per-peer proof. Hosted Nightly and Cursor both found that the intentional coordinated teardown briefly resolved an empty connected-pair set as relay fallback; exact head `af5ddacc04296bbd1d5e00eb9a95f852b05a77a9` suppresses status resolution only for that deliberate gap while preserving automatic-retry and bounded-timeout failure reporting. Final exact head `af5ddacc04296bbd1d5e00eb9a95f852b05a77a9` passed all 19 applicable hosted workflows; Dependabot auto-merge was the sole expected skip.

## Residual risk

Native reference-client interop currently runs on Linux; the root Windows/macOS lanes do not compile this standalone crate, so dedicated cross-platform native-client build coverage remains follow-up work. The focused interop environment selects IPv4, while IPv6 bind scope semantics are pinned directly. This coverage is tracked in #271.

Closes #268

---

> [!NOTE]
> **High Risk**
> Large dependency and API migration on the CI-enforced native WebRTC interop path, plus an MSRV bump that affects all builds; server wire protocol is unchanged but P2P/fallback behavior is heavily re-tested rather than trivial.
> 
> **Overview**
> **Raises the exact Rust MSRV from 1.89 to 1.91** across `Cargo.toml`, `rust-toolchain.toml`, Docker/devcontainer images, CI workflow comments, Dependabot policy, and docs badges.
> 
> **Migrates the standalone native reference client from webrtc-rs 0.17 to 0.20** (`webrtc` + `rtc` 0.20, `if-addrs` for interface binding). The engine is rewritten around async `PeerConnectionEventHandler`, poll-driven data channels, stats-based selected-candidate reporting, and stripping rtc 0.20’s local-only `url` from ICE wire JSON so Matchbox/browser signaling stays four-field. **Host candidates** bind concrete active interfaces (no wildcard `0.0.0.0`); **`--cripple-ice`** uses loopback UDP plus TCP4-only ICE settings so gathering/SDP still run but no usable local/SDP-embedded UDP candidates connect.
> 
> **Interop harness and client orchestration** add release-file gates for coordinated PairRetry rebuild (`--p2p-rebuild-release-file`), split reliable vs unreliable exchange (`--unreliable-exchange-release-file`), and events `p2p_pair_reconnected` / `exchange_reliable_ready`. Loss-recovery tests require a reserved final retry generation and causal reliable-before-unreliable exchange. **Late-join e2e** holds clients at `--success-release-file`, asserts exact `peer_transport_status` fan-out counts, and compares reporter transition sequences in a pre-teardown window.
> 
> Minor repo-wide cleanups: `index.is_multiple_of(2)` style lints, TURN negative-control stderr string update, CHANGELOG and ADR-0004 amendment.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit af5ddacc04296bbd1d5e00eb9a95f852b05a77a9. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by wallstop** [comment]
@cursor review

**Comment by wallstop** [comment]
bugbot run

**Comment by wallstop** [comment]
@cursor review

**Comment by wallstop** [comment]
bugbot run

**Comment by wallstop** [comment]
@cursor review

Please review exact head `4084bdb`.

**Comment by wallstop** [comment]
bugbot run

Please review exact head `4084bdb`.

**Comment by wallstop** [comment]
@cursor review

Please review exact head `1f76431`.

**Comment by wallstop** [comment]
bugbot run

Please review exact head `1f76431`.

**Comment by wallstop** [comment]
@cursor review

Please review exact head `0b9b427667e792587c42d91f46e52d9e8f50a48c`, including the coordinated post-netem PairRetry rebuild, reserved retry generation, pre-rebuild signal settlement, and causal channel-generation oracle.

**Comment by wallstop** [comment]
bugbot run

Please analyze exact head `0b9b427667e792587c42d91f46e52d9e8f50a48c`.

**Comment by wallstop** [comment]
@cursor review

Correction: please review exact head `0b9b427e5ce4a6f098387826a3921199661ade7c`, including the coordinated post-netem PairRetry rebuild, reserved retry generation, pre-rebuild signal settlement, and causal channel-generation oracle.

**Comment by wallstop** [comment]
bugbot run

Correction: please analyze exact head `0b9b427e5ce4a6f098387826a3921199661ade7c`.

**Comment by wallstop** [comment]
@cursor review

Exact head: `af5ddacc04296bbd1d5e00eb9a95f852b05a77a9`. The prior finding is addressed by suppressing transport-status resolution only during the intentional coordinated teardown gap; automatic retry gaps and bounded-deadline failures still report fallback.

**Comment by wallstop** [comment]
bugbot run

Exact head: `af5ddacc04296bbd1d5e00eb9a95f852b05a77a9`.
