### ISSUE TITLE
chore(native): migrate WebRTC stack after rtc-mdns restores Rust 1.89 compatibility

### ISSUE THREAD

**Issue by wallstop** [Ambiguous-Interactive/signal-fish-server#268]
## Problem

Dependabot PR #265 proposes `webrtc` 0.17.2 → 0.20.0 for `clients/native`, but every workflow that builds the native client fails on the repository's supported Rust 1.89 toolchain:

```text
rtc-mdns-0.20.0/src/proto/mod.rs:633
Ipv4Addr::from_octets(a.a)
error[E0658]: use of unstable library feature `ip_from`
```

`Ipv4Addr::from_octets` is stable only from Rust 1.91. `webrtc` 0.20.0 depends on `rtc` 0.20.0, which unconditionally depends on `rtc-mdns` 0.20.0; the published feature sets do not remove mDNS. All published rtc-mdns 0.20 prereleases and 0.20.0 contain the same call, and the current upstream default branch remains affected.

Raising this repository's MSRV from 1.89 to 1.91 or carrying an unreviewed git/path patch is disproportionate for a routine dependency update. Keep `webrtc` 0.17 until an official compatible release is available.

## Upstream evidence

- Rust 1.91 release: https://github.com/rust-lang/rust/releases/tag/1.91.0
- Affected upstream source: https://github.com/webrtc-rs/rtc/blob/b1f30eae5ab10bd02688b91febb20e17d8fec159/rtc-mdns/src/proto/mod.rs#L633
- Published rtc-mdns versions: https://crates.io/crates/rtc-mdns/versions
- Exact Rust 1.89 compilation reports `ip_from` as unstable; Rust's source stability annotation records `since = "1.91.0"`.

## Acceptance criteria

- [ ] An official crates.io `rtc`/`webrtc` release builds on exact Rust 1.89, or the project makes an explicit coordinated MSRV decision.
- [ ] Migrate the native reference-client source for the WebRTC 0.20+ Sans-I/O rewrite; do not treat this as a lockfile-only update.
- [ ] `cargo +1.89.0 check --locked --manifest-path clients/native/Cargo.toml --all-features` passes.
- [ ] Native WebRTC, browser/native, and TURN-only interop runners pass.
- [ ] Relevant nightly multi-process/topology and starved-runtime matrices pass.
- [ ] No temporary git/path patch is introduced unless separately reviewed and justified for supply-chain/security reasons.

## Related

- Dependabot PR #265
- Issue #255 / the production zero-panic and exact-MSRV policy

**Comment by wallstop** [comment]
Owner decision: I think it's fine to raise minimum rust version here.
